apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/euanhume/gitops-examples
    targetRevision: HEAD
    path: ./bookinfo/base
  destination:
    namespace: bookinfo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true